[bell]
duration = 0

[colors.bright]
black = "#5c6370"
blue = "#a7d9ff"
cyan = "#5c7ba3"
green = "#a2e5a0"
magenta = "#3d8197"
red = "#e57e7e"
white = "#ffffff"
yellow = "#efe9b3"

[colors.cursor]
cursor = "#9dcbfb"
text = "#101418"

[colors.normal]
black = "#101418"
blue = "#4087bc"
cyan = "#9dcbfb"
green = "#8ed88c"
magenta = "#839fbc"
red = "#d75a59"
white = "#abb2bf"
yellow = "#e0d99d"

[colors.primary]
background = "#101418"
foreground = "#e0e2e8"

[colors.selection]
background = "#124a73"
text = "#e0e2e8"

[cursor]
blink_interval = 500
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 16.0

[font.normal]
family = "DroidSansM Nerd Font"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
chars = "\n"
key = "Enter"
mods = "Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 3023
multiplier = 3

[selection]
save_to_clipboard = false

[terminal]
osc52 = "CopyPaste"

[window]
blur = true
dynamic_padding = true
dynamic_title = true
opacity = 1.0
option_as_alt = "Both"
startup_mode = "Maximized"

[window.padding]
x = 12
y = 12
