"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$character
"""

[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = true
fish_style_pwd_dir_length = 1

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold yellow)"

[git_branch]
symbol = "󰊢 "
style = "bold white"
format = "[$symbol$branch]($style) "

[git_status]
style = "red"
format = "([$all_status$ahead_behind]($style) )"
conflicted = "!"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
untracked = "?"
stashed = "\\$"
modified = "~"
staged = "+"
renamed = "»"
deleted = "✘"

[package]
format = 'is [$symbol$version]($style) '

version_format = 'v${major}.${minor}'

[nodejs]
version_format = '${major}.${minor}'

[python]
format = 'via [🐍 $version]($style) '
version_format = 'v${major}.${minor}'
disabled = false

[lua]
disabled = true

[golang]
disabled = true

[rust]
disabled = true

[docker_context]
disabled = true

[kubernetes]
disabled = true

# Misc

[cmd_duration]
disabled = true

[time]
disabled = true
