# background = #1e1e1e

background= #000000
foreground = #f5f5f7

cursor-color = #007aff
cursor-text = #1e1e1e
cursor-style = block
cursor-style-blink = true

selection-background = #0058d0
selection-foreground = #ffffff

# Normal colors (0-7)
palette = 0=#1e1e1e
palette = 1=#ff453a
palette = 2=#30d158
palette = 3=#ffd60a
palette = 4=#0a84ff
palette = 5=#bf5af2
palette = 6=#64d2ff
palette = 7=#e5e5ea

# Bright colors (8-15)
palette = 8=#636366
palette = 9=#ff6961
palette = 10=#32d74b
palette = 11=#ffdf00
palette = 12=#409cff
palette = 13=#da8fff
palette = 14=#70d7ff
palette = 15=#ffffff
