# Window
confirm-close-surface = true
copy-on-select = true
macos-option-as-alt = true
macos-titlebar-proxy-icon = hidden
maximize = true
mouse-hide-while-typing = true
scrollback-limit = 50000
shell-integration = detect
window-padding-x = 10
window-padding-y = 10
window-theme = dark
# macos-titlebar-style = transparent
macos-titlebar-style = hidden
background-opacity = 0.85
background-blur-radius = 20
background-blur = 16
