# Window
background-opacity = 1
confirm-close-surface = true
copy-on-select = true
macos-option-as-alt = true
macos-titlebar-proxy-icon = hidden
macos-titlebar-style = tabs
maximize = true
mouse-hide-while-typing = true
scrollback-limit = 50000
shell-integration = detect
window-padding-x = 10
window-padding-y = 10
window-theme = dark
