set -g status-position top
set -g status-interval 5
set -g status-style "bg=#080a0d,fg=#8d96a3"
set -g status-left "#[fg=#7dd3fc,bold] #S #[fg=#2a3441]│"
set -g status-left-length 28
set -g status-right "#[fg=#2a3441]│ #[fg=#8d96a3]%H:%M "
set -g status-right-length 16
set -g window-status-format "#[fg=#5c6370] #I:#W "
set -g window-status-current-format "#[fg=#080a0d,bg=#7dd3fc,bold] #I:#W "
set -g window-status-separator " "
set -g pane-border-style "fg=#1d2633"
set -g pane-active-border-style "fg=#56b6c2"
set -g display-panes-colour "#5c6370"
set -g display-panes-active-colour "#7dd3fc"
set -g message-style "bg=#11151c,fg=#d7dce2"
set -g message-command-style "bg=#11151c,fg=#7dd3fc"
set -g mode-style "bg=#243244,fg=#f2f5f8"

setw -g monitor-activity on
set -g visual-activity off
set -g window-status-activity-style "fg=#e5b07d"
